name: Publish Crate

on:
  push:
    tags:
      - "*"

jobs:
  publish:
    name: Check, Test, and Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Check the crate builds
        run: cargo check --all-targets --all-features

      - name: Run tests
        run: cargo test --all-targets --all-features --no-fail-fast

      - name: Publish to crates.io
        run: cargo publish --locked
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
